version: '3.0'
services:
  candig-server:
    image: candig-server
    build: candig-server
    ports:
      - 80/tcp
  beacon:
    image: beacon
    build: .
    ports:
      - 8080/tcp
    environment:
      CANDIG_HOST: candig-server
