version: '3.0'
services:
  candig-server:
    image: candig-server
    build: candig-server
    ports:
      - 80/tcp
  beacon:
    image: beacon
    build: .
    ports:
      - 8080/tcp
    links:
      - candig-server:candig
      - redis
  redis:
    image: redis
