version: '3.0'
services:
  candig-server:
    build: candig-server
    ports:
      - 80/tcp
    volumes:
      - ./testdata:/moredata
      - /data

  beacon:
    build: .
    environment:
      BEACON_VERBOSE: ${BEACON_VERBOSE}
    depends_on:
      - candig-server

  haproxy:
    image: haproxy
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - 80/tcp
