version: '3.0'
services:
  candig-server:
    image: candig-server
    build: candig-server
    ports:
      - 80/tcp

  beacon:
    image: beacon
    build: .
    environment:
      CANDIG_URL: http://candig-server/
    depends_on:
      - candig-server

  haproxy:
    build: proxy
    ports:
      - 80/tcp
    environment:
      BACKEND: beacon:8080
