version: '3.0'
services:
  candig-server:
    build: candig-server
    ports:
      - 80/tcp
  beacon:
    build: .
    ports:
      - 8080/tcp
    environment:
      CANDIG_SERVER: http://candig-server
