/*
 * CanDIG Services
 *
 * Below is a list of APIs that CanDIG currently supports.<br/><br/>For /search and /count endpoints, refer to [this documentation](https://www.distributedgenomics.ca/static/search_count_services_usage.pdf) for instructions and sample queries.<br/>For all metadata and variant services endpoints, refer to [this documentation](https://www.distributedgenomics.ca/static/metadata_variants_services_sample_queries.pdf) for sample queries.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

import (
	"encoding/json"
)

// Ga4ghSearchRnaQuantificationSetsResponse This is the response from 'POST /rnaquantificationsets/search' expressed as JSON.
type Ga4ghSearchRnaQuantificationSetsResponse struct {
	// The list of matching quantification sets.
	RnaQuantificationSets *[]Ga4ghRnaQuantificationSet `json:"rna_quantification_sets,omitempty"`

	// The continuation token, which is used to page through large result sets. To get the next page of results, set this parameter to the value of 'nextPageToken' from the previous response.
	NextPageToken *string `json:"next_page_token,omitempty"`
}

// GetRnaQuantificationSets returns the RnaQuantificationSets field if non-nil, zero value otherwise.
func (o *Ga4ghSearchRnaQuantificationSetsResponse) GetRnaQuantificationSets() []Ga4ghRnaQuantificationSet {
	if o == nil || o.RnaQuantificationSets == nil {
		var ret []Ga4ghRnaQuantificationSet
		return ret
	}
	return *o.RnaQuantificationSets
}

// GetRnaQuantificationSetsOk returns a tuple with the RnaQuantificationSets field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *Ga4ghSearchRnaQuantificationSetsResponse) GetRnaQuantificationSetsOk() ([]Ga4ghRnaQuantificationSet, bool) {
	if o == nil || o.RnaQuantificationSets == nil {
		var ret []Ga4ghRnaQuantificationSet
		return ret, false
	}
	return *o.RnaQuantificationSets, true
}

// HasRnaQuantificationSets returns a boolean if a field has been set.
func (o *Ga4ghSearchRnaQuantificationSetsResponse) HasRnaQuantificationSets() bool {
	if o != nil && o.RnaQuantificationSets != nil {
		return true
	}

	return false
}

// SetRnaQuantificationSets gets a reference to the given []Ga4ghRnaQuantificationSet and assigns it to the RnaQuantificationSets field.
func (o *Ga4ghSearchRnaQuantificationSetsResponse) SetRnaQuantificationSets(v []Ga4ghRnaQuantificationSet) {
	o.RnaQuantificationSets = &v
}

// GetNextPageToken returns the NextPageToken field if non-nil, zero value otherwise.
func (o *Ga4ghSearchRnaQuantificationSetsResponse) GetNextPageToken() string {
	if o == nil || o.NextPageToken == nil {
		var ret string
		return ret
	}
	return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *Ga4ghSearchRnaQuantificationSetsResponse) GetNextPageTokenOk() (string, bool) {
	if o == nil || o.NextPageToken == nil {
		var ret string
		return ret, false
	}
	return *o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *Ga4ghSearchRnaQuantificationSetsResponse) HasNextPageToken() bool {
	if o != nil && o.NextPageToken != nil {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *Ga4ghSearchRnaQuantificationSetsResponse) SetNextPageToken(v string) {
	o.NextPageToken = &v
}

// MarshalJSON returns the JSON representation of the model.
func (o Ga4ghSearchRnaQuantificationSetsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.RnaQuantificationSets != nil {
		toSerialize["rna_quantification_sets"] = o.RnaQuantificationSets
	}
	if o.NextPageToken != nil {
		toSerialize["next_page_token"] = o.NextPageToken
	}
	return json.Marshal(toSerialize)
}
