/*
 * CanDIG Services
 *
 * Below is a list of APIs that CanDIG currently supports.<br/><br/>For /search and /count endpoints, refer to [this documentation](https://www.distributedgenomics.ca/static/search_count_services_usage.pdf) for instructions and sample queries.<br/>For all metadata and variant services endpoints, refer to [this documentation](https://www.distributedgenomics.ca/static/metadata_variants_services_sample_queries.pdf) for sample queries.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

import (
	"encoding/json"
)

// Ga4ghSearchTreatmentsResponse This is the response from `POST /treatments/search` expressed as JSON.
type Ga4ghSearchTreatmentsResponse struct {
	// The list of treatments.
	Treatments *[]Ga4ghTreatment `json:"treatments,omitempty"`

	// The continuation token, which is used to page through large result sets. Provide this value in a subsequent request to return the next page of results. This field will be empty if there aren't any additional results.
	NextPageToken *string `json:"next_page_token,omitempty"`
}

// GetTreatments returns the Treatments field if non-nil, zero value otherwise.
func (o *Ga4ghSearchTreatmentsResponse) GetTreatments() []Ga4ghTreatment {
	if o == nil || o.Treatments == nil {
		var ret []Ga4ghTreatment
		return ret
	}
	return *o.Treatments
}

// GetTreatmentsOk returns a tuple with the Treatments field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *Ga4ghSearchTreatmentsResponse) GetTreatmentsOk() ([]Ga4ghTreatment, bool) {
	if o == nil || o.Treatments == nil {
		var ret []Ga4ghTreatment
		return ret, false
	}
	return *o.Treatments, true
}

// HasTreatments returns a boolean if a field has been set.
func (o *Ga4ghSearchTreatmentsResponse) HasTreatments() bool {
	if o != nil && o.Treatments != nil {
		return true
	}

	return false
}

// SetTreatments gets a reference to the given []Ga4ghTreatment and assigns it to the Treatments field.
func (o *Ga4ghSearchTreatmentsResponse) SetTreatments(v []Ga4ghTreatment) {
	o.Treatments = &v
}

// GetNextPageToken returns the NextPageToken field if non-nil, zero value otherwise.
func (o *Ga4ghSearchTreatmentsResponse) GetNextPageToken() string {
	if o == nil || o.NextPageToken == nil {
		var ret string
		return ret
	}
	return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *Ga4ghSearchTreatmentsResponse) GetNextPageTokenOk() (string, bool) {
	if o == nil || o.NextPageToken == nil {
		var ret string
		return ret, false
	}
	return *o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *Ga4ghSearchTreatmentsResponse) HasNextPageToken() bool {
	if o != nil && o.NextPageToken != nil {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *Ga4ghSearchTreatmentsResponse) SetNextPageToken(v string) {
	o.NextPageToken = &v
}

// MarshalJSON returns the JSON representation of the model.
func (o Ga4ghSearchTreatmentsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Treatments != nil {
		toSerialize["treatments"] = o.Treatments
	}
	if o.NextPageToken != nil {
		toSerialize["next_page_token"] = o.NextPageToken
	}
	return json.Marshal(toSerialize)
}
