/*
 * CanDIG Services
 *
 * Below is a list of APIs that CanDIG currently supports.<br/><br/>For /search and /count endpoints, refer to [this documentation](https://www.distributedgenomics.ca/static/search_count_services_usage.pdf) for instructions and sample queries.<br/>For all metadata and variant services endpoints, refer to [this documentation](https://www.distributedgenomics.ca/static/metadata_variants_services_sample_queries.pdf) for sample queries.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
import (
	"encoding/json"
)

// This is the response from `POST /surgeries/search` expressed as JSON.
type Ga4ghSearchSurgeriesResponse struct {
	// The list of surgeries.
	Surgeries *[]Ga4ghSurgery `json:"surgeries,omitempty"`

	// The continuation token, which is used to page through large result sets. Provide this value in a subsequent request to return the next page of results. This field will be empty if there aren't any additional results.
	NextPageToken *string `json:"next_page_token,omitempty"`

}

// GetSurgeries returns the Surgeries field if non-nil, zero value otherwise.
func (o *Ga4ghSearchSurgeriesResponse) GetSurgeries() []Ga4ghSurgery {
	if o == nil || o.Surgeries == nil {
		var ret []Ga4ghSurgery
		return ret
	}
	return *o.Surgeries
}

// GetSurgeriesOk returns a tuple with the Surgeries field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *Ga4ghSearchSurgeriesResponse) GetSurgeriesOk() ([]Ga4ghSurgery, bool) {
	if o == nil || o.Surgeries == nil {
		var ret []Ga4ghSurgery
		return ret, false
	}
	return *o.Surgeries, true
}

// HasSurgeries returns a boolean if a field has been set.
func (o *Ga4ghSearchSurgeriesResponse) HasSurgeries() bool {
	if o != nil && o.Surgeries != nil {
		return true
	}

	return false
}

// SetSurgeries gets a reference to the given []Ga4ghSurgery and assigns it to the Surgeries field.
func (o *Ga4ghSearchSurgeriesResponse) SetSurgeries(v []Ga4ghSurgery) {
	o.Surgeries = &v
}

// GetNextPageToken returns the NextPageToken field if non-nil, zero value otherwise.
func (o *Ga4ghSearchSurgeriesResponse) GetNextPageToken() string {
	if o == nil || o.NextPageToken == nil {
		var ret string
		return ret
	}
	return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *Ga4ghSearchSurgeriesResponse) GetNextPageTokenOk() (string, bool) {
	if o == nil || o.NextPageToken == nil {
		var ret string
		return ret, false
	}
	return *o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *Ga4ghSearchSurgeriesResponse) HasNextPageToken() bool {
	if o != nil && o.NextPageToken != nil {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *Ga4ghSearchSurgeriesResponse) SetNextPageToken(v string) {
	o.NextPageToken = &v
}


func (o Ga4ghSearchSurgeriesResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Surgeries != nil {
		toSerialize["surgeries"] = o.Surgeries
	}
	if o.NextPageToken != nil {
		toSerialize["next_page_token"] = o.NextPageToken
	}
	return json.Marshal(toSerialize)
}


