/*
 * CanDIG Services
 *
 * Below is a list of APIs that CanDIG currently supports.<br/><br/>For /search and /count endpoints, refer to [this documentation](https://www.distributedgenomics.ca/static/search_count_services_usage.pdf) for instructions and sample queries.<br/>For all metadata and variant services endpoints, refer to [this documentation](https://www.distributedgenomics.ca/static/metadata_variants_services_sample_queries.pdf) for sample queries.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

import (
	"encoding/json"
)

// Ga4ghAttributeValueList struct for Ga4ghAttributeValueList
type Ga4ghAttributeValueList struct {
	Values *[]Ga4ghAttributeValue `json:"values,omitempty"`
}

// GetValues returns the Values field if non-nil, zero value otherwise.
func (o *Ga4ghAttributeValueList) GetValues() []Ga4ghAttributeValue {
	if o == nil || o.Values == nil {
		var ret []Ga4ghAttributeValue
		return ret
	}
	return *o.Values
}

// GetValuesOk returns a tuple with the Values field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *Ga4ghAttributeValueList) GetValuesOk() ([]Ga4ghAttributeValue, bool) {
	if o == nil || o.Values == nil {
		var ret []Ga4ghAttributeValue
		return ret, false
	}
	return *o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *Ga4ghAttributeValueList) HasValues() bool {
	if o != nil && o.Values != nil {
		return true
	}

	return false
}

// SetValues gets a reference to the given []Ga4ghAttributeValue and assigns it to the Values field.
func (o *Ga4ghAttributeValueList) SetValues(v []Ga4ghAttributeValue) {
	o.Values = &v
}

// MarshalJSON returns the JSON representation of the model.
func (o Ga4ghAttributeValueList) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Values != nil {
		toSerialize["values"] = o.Values
	}
	return json.Marshal(toSerialize)
}
