/*
 * CanDIG Services
 *
 * Below is a list of APIs that CanDIG currently supports.<br/><br/>For /search and /count endpoints, refer to [this documentation](https://www.distributedgenomics.ca/static/search_count_services_usage.pdf) for instructions and sample queries.<br/>For all metadata and variant services endpoints, refer to [this documentation](https://www.distributedgenomics.ca/static/metadata_variants_services_sample_queries.pdf) for sample queries.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
import (
	"encoding/json"
)

// This is the response from `POST /slides/search` expressed as JSON.
type Ga4ghSearchSlidesResponse struct {
	// The list of slides.
	Slides *[]Ga4ghSlide `json:"slides,omitempty"`

	// The continuation token, which is used to page through large result sets. Provide this value in a subsequent request to return the next page of results. This field will be empty if there aren't any additional results.
	NextPageToken *string `json:"next_page_token,omitempty"`

}

// GetSlides returns the Slides field if non-nil, zero value otherwise.
func (o *Ga4ghSearchSlidesResponse) GetSlides() []Ga4ghSlide {
	if o == nil || o.Slides == nil {
		var ret []Ga4ghSlide
		return ret
	}
	return *o.Slides
}

// GetSlidesOk returns a tuple with the Slides field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *Ga4ghSearchSlidesResponse) GetSlidesOk() ([]Ga4ghSlide, bool) {
	if o == nil || o.Slides == nil {
		var ret []Ga4ghSlide
		return ret, false
	}
	return *o.Slides, true
}

// HasSlides returns a boolean if a field has been set.
func (o *Ga4ghSearchSlidesResponse) HasSlides() bool {
	if o != nil && o.Slides != nil {
		return true
	}

	return false
}

// SetSlides gets a reference to the given []Ga4ghSlide and assigns it to the Slides field.
func (o *Ga4ghSearchSlidesResponse) SetSlides(v []Ga4ghSlide) {
	o.Slides = &v
}

// GetNextPageToken returns the NextPageToken field if non-nil, zero value otherwise.
func (o *Ga4ghSearchSlidesResponse) GetNextPageToken() string {
	if o == nil || o.NextPageToken == nil {
		var ret string
		return ret
	}
	return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *Ga4ghSearchSlidesResponse) GetNextPageTokenOk() (string, bool) {
	if o == nil || o.NextPageToken == nil {
		var ret string
		return ret, false
	}
	return *o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *Ga4ghSearchSlidesResponse) HasNextPageToken() bool {
	if o != nil && o.NextPageToken != nil {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *Ga4ghSearchSlidesResponse) SetNextPageToken(v string) {
	o.NextPageToken = &v
}


func (o Ga4ghSearchSlidesResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Slides != nil {
		toSerialize["slides"] = o.Slides
	}
	if o.NextPageToken != nil {
		toSerialize["next_page_token"] = o.NextPageToken
	}
	return json.Marshal(toSerialize)
}


