/*
 * CanDIG Services
 *
 * Below is a list of APIs that CanDIG currently supports.<br/><br/>For /search and /count endpoints, refer to [this documentation](https://www.distributedgenomics.ca/static/search_count_services_usage.pdf) for instructions and sample queries.<br/>For all metadata and variant services endpoints, refer to [this documentation](https://www.distributedgenomics.ca/static/metadata_variants_services_sample_queries.pdf) for sample queries.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

import (
	"encoding/json"
)

// Ga4ghSearchVariantSetsResponse This is the response from `POST /variantsets/search` expressed as JSON.
type Ga4ghSearchVariantSetsResponse struct {
	// The list of matching variant sets.
	VariantSets *[]Ga4ghVariantSet `json:"variant_sets,omitempty"`

	// The continuation token, which is used to page through large result sets. Provide this value in a subsequent request to return the next page of results. This field will be empty if there aren't any additional results.
	NextPageToken *string `json:"next_page_token,omitempty"`
}

// GetVariantSets returns the VariantSets field if non-nil, zero value otherwise.
func (o *Ga4ghSearchVariantSetsResponse) GetVariantSets() []Ga4ghVariantSet {
	if o == nil || o.VariantSets == nil {
		var ret []Ga4ghVariantSet
		return ret
	}
	return *o.VariantSets
}

// GetVariantSetsOk returns a tuple with the VariantSets field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *Ga4ghSearchVariantSetsResponse) GetVariantSetsOk() ([]Ga4ghVariantSet, bool) {
	if o == nil || o.VariantSets == nil {
		var ret []Ga4ghVariantSet
		return ret, false
	}
	return *o.VariantSets, true
}

// HasVariantSets returns a boolean if a field has been set.
func (o *Ga4ghSearchVariantSetsResponse) HasVariantSets() bool {
	if o != nil && o.VariantSets != nil {
		return true
	}

	return false
}

// SetVariantSets gets a reference to the given []Ga4ghVariantSet and assigns it to the VariantSets field.
func (o *Ga4ghSearchVariantSetsResponse) SetVariantSets(v []Ga4ghVariantSet) {
	o.VariantSets = &v
}

// GetNextPageToken returns the NextPageToken field if non-nil, zero value otherwise.
func (o *Ga4ghSearchVariantSetsResponse) GetNextPageToken() string {
	if o == nil || o.NextPageToken == nil {
		var ret string
		return ret
	}
	return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *Ga4ghSearchVariantSetsResponse) GetNextPageTokenOk() (string, bool) {
	if o == nil || o.NextPageToken == nil {
		var ret string
		return ret, false
	}
	return *o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *Ga4ghSearchVariantSetsResponse) HasNextPageToken() bool {
	if o != nil && o.NextPageToken != nil {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *Ga4ghSearchVariantSetsResponse) SetNextPageToken(v string) {
	o.NextPageToken = &v
}

// MarshalJSON returns the JSON representation of the model.
func (o Ga4ghSearchVariantSetsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.VariantSets != nil {
		toSerialize["variant_sets"] = o.VariantSets
	}
	if o.NextPageToken != nil {
		toSerialize["next_page_token"] = o.NextPageToken
	}
	return json.Marshal(toSerialize)
}
