/*
 * CanDIG Services
 *
 * Below is a list of APIs that CanDIG currently supports.<br/><br/>For /search and /count endpoints, refer to [this documentation](https://www.distributedgenomics.ca/static/search_count_services_usage.pdf) for instructions and sample queries.<br/>For all metadata and variant services endpoints, refer to [this documentation](https://www.distributedgenomics.ca/static/metadata_variants_services_sample_queries.pdf) for sample queries.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
type Ga4ghExpressionUnit string

// List of ga4ghExpressionUnit
const (
	EXPRESSION_UNIT_UNSPECIFIED Ga4ghExpressionUnit = "EXPRESSION_UNIT_UNSPECIFIED"
	FPKM Ga4ghExpressionUnit = "FPKM"
	TPM Ga4ghExpressionUnit = "TPM"
	RPKM Ga4ghExpressionUnit = "RPKM"
)

