/*
 * CanDIG Services
 *
 * Below is a list of APIs that CanDIG currently supports.<br/><br/>For /search and /count endpoints, refer to [this documentation](https://www.distributedgenomics.ca/static/search_count_services_usage.pdf) for instructions and sample queries.<br/>For all metadata and variant services endpoints, refer to [this documentation](https://www.distributedgenomics.ca/static/metadata_variants_services_sample_queries.pdf) for sample queries.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

import (
	"encoding/json"
)

// Ga4ghSearchDiagnosesResponse This is the response from `POST /diagnoses/search` expressed as JSON.
type Ga4ghSearchDiagnosesResponse struct {
	// The list of diagnoses.
	Diagnoses *[]Ga4ghDiagnosis `json:"diagnoses,omitempty"`

	// The continuation token, which is used to page through large result sets. Provide this value in a subsequent request to return the next page of results. This field will be empty if there aren't any additional results.
	NextPageToken *string `json:"next_page_token,omitempty"`
}

// GetDiagnoses returns the Diagnoses field if non-nil, zero value otherwise.
func (o *Ga4ghSearchDiagnosesResponse) GetDiagnoses() []Ga4ghDiagnosis {
	if o == nil || o.Diagnoses == nil {
		var ret []Ga4ghDiagnosis
		return ret
	}
	return *o.Diagnoses
}

// GetDiagnosesOk returns a tuple with the Diagnoses field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *Ga4ghSearchDiagnosesResponse) GetDiagnosesOk() ([]Ga4ghDiagnosis, bool) {
	if o == nil || o.Diagnoses == nil {
		var ret []Ga4ghDiagnosis
		return ret, false
	}
	return *o.Diagnoses, true
}

// HasDiagnoses returns a boolean if a field has been set.
func (o *Ga4ghSearchDiagnosesResponse) HasDiagnoses() bool {
	if o != nil && o.Diagnoses != nil {
		return true
	}

	return false
}

// SetDiagnoses gets a reference to the given []Ga4ghDiagnosis and assigns it to the Diagnoses field.
func (o *Ga4ghSearchDiagnosesResponse) SetDiagnoses(v []Ga4ghDiagnosis) {
	o.Diagnoses = &v
}

// GetNextPageToken returns the NextPageToken field if non-nil, zero value otherwise.
func (o *Ga4ghSearchDiagnosesResponse) GetNextPageToken() string {
	if o == nil || o.NextPageToken == nil {
		var ret string
		return ret
	}
	return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *Ga4ghSearchDiagnosesResponse) GetNextPageTokenOk() (string, bool) {
	if o == nil || o.NextPageToken == nil {
		var ret string
		return ret, false
	}
	return *o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *Ga4ghSearchDiagnosesResponse) HasNextPageToken() bool {
	if o != nil && o.NextPageToken != nil {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *Ga4ghSearchDiagnosesResponse) SetNextPageToken(v string) {
	o.NextPageToken = &v
}

// MarshalJSON returns the JSON representation of the model.
func (o Ga4ghSearchDiagnosesResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Diagnoses != nil {
		toSerialize["diagnoses"] = o.Diagnoses
	}
	if o.NextPageToken != nil {
		toSerialize["next_page_token"] = o.NextPageToken
	}
	return json.Marshal(toSerialize)
}
