/*
 * CanDIG Services
 *
 * Below is a list of APIs that CanDIG currently supports.<br/><br/>For /search and /count endpoints, refer to [this documentation](https://www.distributedgenomics.ca/static/search_count_services_usage.pdf) for instructions and sample queries.<br/>For all metadata and variant services endpoints, refer to [this documentation](https://www.distributedgenomics.ca/static/metadata_variants_services_sample_queries.pdf) for sample queries.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

import (
	"encoding/json"
)

// Ga4ghSearchAlignmentsResponse This is the response from `POST /alignments/search` expressed as JSON.
type Ga4ghSearchAlignmentsResponse struct {
	// The list of alignments.
	Alignments *[]Ga4ghAlignment `json:"alignments,omitempty"`

	// The continuation token, which is used to page through large result sets.Provide this value in a subsequent request to return the next page ofresults. This field will be empty if there aren't any additional results.
	NextPageToken *string `json:"next_page_token,omitempty"`
}

// GetAlignments returns the Alignments field if non-nil, zero value otherwise.
func (o *Ga4ghSearchAlignmentsResponse) GetAlignments() []Ga4ghAlignment {
	if o == nil || o.Alignments == nil {
		var ret []Ga4ghAlignment
		return ret
	}
	return *o.Alignments
}

// GetAlignmentsOk returns a tuple with the Alignments field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *Ga4ghSearchAlignmentsResponse) GetAlignmentsOk() ([]Ga4ghAlignment, bool) {
	if o == nil || o.Alignments == nil {
		var ret []Ga4ghAlignment
		return ret, false
	}
	return *o.Alignments, true
}

// HasAlignments returns a boolean if a field has been set.
func (o *Ga4ghSearchAlignmentsResponse) HasAlignments() bool {
	if o != nil && o.Alignments != nil {
		return true
	}

	return false
}

// SetAlignments gets a reference to the given []Ga4ghAlignment and assigns it to the Alignments field.
func (o *Ga4ghSearchAlignmentsResponse) SetAlignments(v []Ga4ghAlignment) {
	o.Alignments = &v
}

// GetNextPageToken returns the NextPageToken field if non-nil, zero value otherwise.
func (o *Ga4ghSearchAlignmentsResponse) GetNextPageToken() string {
	if o == nil || o.NextPageToken == nil {
		var ret string
		return ret
	}
	return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *Ga4ghSearchAlignmentsResponse) GetNextPageTokenOk() (string, bool) {
	if o == nil || o.NextPageToken == nil {
		var ret string
		return ret, false
	}
	return *o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *Ga4ghSearchAlignmentsResponse) HasNextPageToken() bool {
	if o != nil && o.NextPageToken != nil {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *Ga4ghSearchAlignmentsResponse) SetNextPageToken(v string) {
	o.NextPageToken = &v
}

// MarshalJSON returns the JSON representation of the model.
func (o Ga4ghSearchAlignmentsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Alignments != nil {
		toSerialize["alignments"] = o.Alignments
	}
	if o.NextPageToken != nil {
		toSerialize["next_page_token"] = o.NextPageToken
	}
	return json.Marshal(toSerialize)
}
