/*
 * CanDIG Services
 *
 * Below is a list of APIs that CanDIG currently supports.<br/><br/>For /search and /count endpoints, refer to [this documentation](https://www.distributedgenomics.ca/static/search_count_services_usage.pdf) for instructions and sample queries.<br/>For all metadata and variant services endpoints, refer to [this documentation](https://www.distributedgenomics.ca/static/metadata_variants_services_sample_queries.pdf) for sample queries.
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client
import (
	"encoding/json"
)

// This is the response from `POST /expressionanalysis/search` expressed as JSON.
type Ga4ghSearchExpressionAnalysisResponse struct {
	// The list of expression analysis.
	Expressionanalysis *[]Ga4ghExpressionAnalysis `json:"expressionanalysis,omitempty"`

	// The continuation token, which is used to page through large result sets.Provide this value in a subsequent request to return the next page ofresults. This field will be empty if there aren't any additional results.
	NextPageToken *string `json:"next_page_token,omitempty"`

}

// GetExpressionanalysis returns the Expressionanalysis field if non-nil, zero value otherwise.
func (o *Ga4ghSearchExpressionAnalysisResponse) GetExpressionanalysis() []Ga4ghExpressionAnalysis {
	if o == nil || o.Expressionanalysis == nil {
		var ret []Ga4ghExpressionAnalysis
		return ret
	}
	return *o.Expressionanalysis
}

// GetExpressionanalysisOk returns a tuple with the Expressionanalysis field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *Ga4ghSearchExpressionAnalysisResponse) GetExpressionanalysisOk() ([]Ga4ghExpressionAnalysis, bool) {
	if o == nil || o.Expressionanalysis == nil {
		var ret []Ga4ghExpressionAnalysis
		return ret, false
	}
	return *o.Expressionanalysis, true
}

// HasExpressionanalysis returns a boolean if a field has been set.
func (o *Ga4ghSearchExpressionAnalysisResponse) HasExpressionanalysis() bool {
	if o != nil && o.Expressionanalysis != nil {
		return true
	}

	return false
}

// SetExpressionanalysis gets a reference to the given []Ga4ghExpressionAnalysis and assigns it to the Expressionanalysis field.
func (o *Ga4ghSearchExpressionAnalysisResponse) SetExpressionanalysis(v []Ga4ghExpressionAnalysis) {
	o.Expressionanalysis = &v
}

// GetNextPageToken returns the NextPageToken field if non-nil, zero value otherwise.
func (o *Ga4ghSearchExpressionAnalysisResponse) GetNextPageToken() string {
	if o == nil || o.NextPageToken == nil {
		var ret string
		return ret
	}
	return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field if it's non-nil, zero value otherwise
// and a boolean to check if the value has been set.
func (o *Ga4ghSearchExpressionAnalysisResponse) GetNextPageTokenOk() (string, bool) {
	if o == nil || o.NextPageToken == nil {
		var ret string
		return ret, false
	}
	return *o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *Ga4ghSearchExpressionAnalysisResponse) HasNextPageToken() bool {
	if o != nil && o.NextPageToken != nil {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *Ga4ghSearchExpressionAnalysisResponse) SetNextPageToken(v string) {
	o.NextPageToken = &v
}


func (o Ga4ghSearchExpressionAnalysisResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Expressionanalysis != nil {
		toSerialize["expressionanalysis"] = o.Expressionanalysis
	}
	if o.NextPageToken != nil {
		toSerialize["next_page_token"] = o.NextPageToken
	}
	return json.Marshal(toSerialize)
}


