/*
 * GA4GH Beacon API Specification
 *
 * A Beacon is a web service for genetic data sharing that can be queried for information about specific alleles.
 *
 * API version: 1.0.1
 * Contact: beacon@ga4gh.org
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type BeaconAlleleResponse struct {

	// Identifier of the beacon, as defined in `Beacon`.
	BeaconId string `json:"beaconId"`

	// Version of the API. If specified, the value must match `apiVersion` in Beacon
	ApiVersion string `json:"apiVersion,omitempty"`

	// Indicator of whether the given allele was observed in any of the datasets queried. This should be non-null, unless there was an error, in which case `error` has to be non-null.
	Exists bool `json:"exists,omitempty"`

	AlleleRequest BeaconAlleleRequest `json:"alleleRequest,omitempty"`

	// Indicator of whether the given allele was  observed in individual datasets. This should be non-null if `includeDatasetResponses` in the corresponding `BeaconAlleleRequest` is true, and null otherwise.
	DatasetAlleleResponses []BeaconDatasetAlleleResponse `json:"datasetAlleleResponses,omitempty"`

	Error BeaconError `json:"error,omitempty"`
}
