/*
 * GA4GH Beacon API Specification
 *
 * A Beacon is a web service for genetic data sharing that can be queried for information about specific alleles.
 *
 * API version: 1.0.1
 * Contact: beacon@ga4gh.org
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type ResearchProfile string

// List of ResearchProfile
const (
	OTHERr      ResearchProfile = "OTHER"
	METHODS     ResearchProfile = "METHODS"
	CONTROL     ResearchProfile = "CONTROL"
	POPULATION  ResearchProfile = "POPULATION"
	ANCESTRY    ResearchProfile = "ANCESTRY"
	BIOMEDICAL  ResearchProfile = "BIOMEDICAL"
	FUNDAMENTAL ResearchProfile = "FUNDAMENTAL"
	GENETIC     ResearchProfile = "GENETIC"
	DRUG        ResearchProfile = "DRUG"
	DISEASEr    ResearchProfile = "DISEASE"
	GENDER      ResearchProfile = "GENDER"
	AGE         ResearchProfile = "AGE"
)
